### ISSUE TITLE
How should this error be resolved？

### ISSUE THREAD

**Issue by xulinxulin** [SysCV/pcan#12]
creating index...
index created!
2022-04-17 21:40:15,020 - pcan - INFO - Start running, host: lin@lin, work_dir: /home/lin/Desktop/pcan/work_dirs/4.17
2022-04-17 21:40:15,020 - pcan - INFO - workflow: [('train', 1)], max: 12 epochs
/home/lin/.conda/envs/pcan/lib/python3.6/site-packages/mmdet/models/dense_heads/rpn_head.py:180: UserWarning: In rpn_proposal or test_cfg, nms_thr has been moved to a dict named nms as iou_threshold, max_num has been renamed as max_per_img, name of original arguments and the way to specify iou_threshold of NMS will be deprecated.
  'In rpn_proposal or test_cfg, '
Traceback (most recent call last):
  File "tools/train.py", line 168, in <module>
    main()
  File "tools/train.py", line 164, in main
    meta=meta)
  File "/home/lin/Desktop/pcan/pcan/apis/train.py", line 123, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/lin/.conda/envs/pcan/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 125, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/lin/.conda/envs/pcan/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True)
  File "/home/lin/.conda/envs/pcan/lib/python3.6/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/lin/.conda/envs/pcan/lib/python3.6/site-packages/mmcv/parallel/data_parallel.py", line 67, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/lin/.conda/envs/pcan/lib/python3.6/site-packages/mmdet/models/detectors/base.py", line 247, in train_step
    losses = self(**data)
  File "/home/lin/.conda/envs/pcan/lib/python3.6/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/lin/Desktop/pcan/pcan/models/mot/quasi_dense_pcan.py", line 45, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home/lin/Desktop/pcan/pcan/models/mot/quasi_dense_pcan.py", line 86, in forward_train
    ref_gt_bboxes_ignore, ref_gt_masks, **kwargs)
  File "/home/lin/Desktop/pcan/pcan/models/roi_heads/quasi_dense_roi_head.py", line 173, in forward_train
    if mask_results['loss_dice'] is not None:
KeyError: 'loss_dice'

**Comment by lkeab** [comment]
what's your command on executing the program leading to this error? Did you use "bash scripts/train_pcan.sh"?

**Comment by xulinxulin** [comment]
The command I use is：python tools/train.py  configs/segtrack-frcnn_r50_fpn_12e_bdd10k.py --work-dir work_dirs/4.17

If  use this command, no errors."bash scripts/train_pcan.sh"

Why is that?

**Comment by lkeab** [comment]
they are using the different config files. Please follow our script usage.
