### ISSUE TITLE
OSError: ./ckpts/segtrack-fixed-new.pth is not a checkpoint file

### ISSUE THREAD

**Issue by hyping111** [SysCV/pcan#15]
I followed your instructions to download the initial model weights and put it under ckpts folder. And I only set the configuration file : configs/segtrack-frcnn_r50_fpn_12e_bdd10k_fixed_pcan.py. But when I run train.py, I got the following error:

Traceback (most recent call last):
  File "/home/dlz/PCAN/tools/train.py", line 175, in <module>
    main()
  File "/home/dlz/PCAN/tools/train.py", line 171, in main
    meta=meta)
  File "/home/dlz/PCAN/pcan/apis/train.py", line 122, in train_model
    runner.load_checkpoint(cfg.load_from)
  File "/home/dlz/anaconda3/envs/pcan/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 313, in load_checkpoint
    self.logger)
  File "/home/dlz/anaconda3/envs/pcan/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 522, in load_checkpoint
    checkpoint = _load_checkpoint(filename, map_location, logger)
  File "/home/dlz/anaconda3/envs/pcan/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 466, in _load_checkpoint
    return CheckpointLoader.load_checkpoint(filename, map_location, logger)
  File "/home/dlz/anaconda3/envs/pcan/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 243, in load_checkpoint
    return checkpoint_loader(filename, map_location)
  File "/home/dlz/anaconda3/envs/pcan/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 259, in load_from_local
    raise IOError(f'{filename} is not a checkpoint file')
OSError: ./ckpts/segtrack-fixed-new.pth is not a checkpoint file

Is there a problem with the given file? Do you have a suggested solution please? Thanks a lot for your answer!

**Comment by lkeab** [comment]
The given file has no problem. You could check its model size. Please refer to the discussions [here](https://github.com/open-mmlab/mmdetection3d/issues/1048) and [here](https://github.com/open-mmlab/mmdetection/issues/1378).

**Comment by hyping111** [comment]
I changed the path to the absolute path and the problem has been solved.Thank you very much!
