### ISSUE TITLE
No BDD100K format jsons generated after running convert_to_bdd.sh

### ISSUE THREAD

**Issue by f414158949** [SysCV/pcan#20]
No BDD100K format jsons (for MOTS challenge submit) generated after running convert_to_bdd.sh.
After running convert_to_bdd.sh, In pcan-main/converted_results/seg_track dir, png masks generated but I can not find json files.

my convert_to_bdd.sh:
python ./tools/to_bdd100k.py configs/segtrack-frcnn_r50_fpn_12e_bdd10k_fixed_pcan.py --res eval_result_pcan_test.pkl \
--task 'seg_track' --bdd-dir converted_results

**Comment by lkeab** [comment]
The benchmark used to also accept the png masks files but it has changed recently. To get the json, install the latest bdd100k api (https://github.com/bdd100k/bdd100k) and run following command:

`python -m bdd100k.label.to_rle -i dir/to/bitmasks -o output.json -m seg_track`

**Comment by f414158949** [comment]
> The benchmark used to also accept the png masks (bit masks) files but it has changed recently. To get the json, install the latest bdd100k api (https://github.com/bdd100k/bdd100k) and run following command:
> 
> `python -m bdd100k.label.to_rle -i dir/to/bitmasks -o output.json -m seg_track`
> 
> "-i", "--input", help=("directory of bitmasks to convert") "-o", "--output", help="path to save scalabel (bdd100k) formatted label file with RLEs"
> 
> You can reference to this [file](https://github.com/bdd100k/bdd100k/blob/master/bdd100k/label/to_rle.py).

Thank you for your reply! I run the bdd100k.label.to_rle command and successfully get the output.json (one JSON file of the entire validation set). I want to submit it to ECCV2022 BDD100K Multiple Object Tracking and Segmentation Challenges(https://eval.ai/web/challenges/challenge-page/1834/overview) , but i get error as follow:


Traceback (most recent call last):
  File "/code/scripts/workers/submission_worker.py", line 491, in run_submission
    submission_metadata=submission_serializer.data,
  File "/tmp/tmp2tp1i0z9/compute/challenge_data/challenge_1834/main.py", line 103, in evaluate
    nproc=1,
  File "/usr/local/lib/python3.7/site-packages/scalabel/eval/seg_track.py", line 46, in evaluate_seg_track_all
    hota_result = evaluate_seg_track_hota(gts, results, config, nproc)
  File "/usr/local/lib/python3.7/site-packages/scalabel/eval/hotas.py", line 237, in evaluate_seg_track_hota
    assert len(gts) == len(results)
AssertionError

**Comment by lkeab** [comment]
Hi have you solved this problem?

**Comment by floveqq** [comment]
> videoName

Could you tell me how to solve this problem? What's wrong with 'videoName' and how you modify it? Thanks very much.

**Comment by cui19981127** [comment]
> Could you tell me how to solve this problem? What's wrong with 'videoName' and how you modify it? Thanks very much.

Could you tell me how to solve this problem? What's wrong with 'videoName' and how you modify it? Thanks very much.

**Comment by cui19981127** [comment]
> yes, I fixed the "videoName" in the json and solved this problem.

Could you tell me how to solve this problem? What's wrong with 'videoName' and how you modify it? Thanks very much.
