### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by cui19981127** [SysCV/pcan#33]
I encountered an issue while training your PCAN network. May I ask for your advice on a solution.When I used my own dataset and tags for training, there was a judgment error when the number of training rounds reached two rounds of comparison results. I couldn't find the reason. Can you take the time to help me solve it.Here is the complete error message.
Python: 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 05:35:01) [MSC v.1916 64 bit (AMD64)]
CUDA available: True
CUDA_HOME: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7
NVCC: Not Available
GPU 0: NVIDIA GeForce RTX 4070 Ti
PyTorch: 1.13.1+cu117
PyTorch compiling details: PyTorch built with:
  - C++ Version: 199711
  - MSVC 192829337
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 2019
  - LAPACK is enabled (usually provided by MKL)
  - CPU capability usage: AVX2
  - CUDA Runtime 11.7
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.5
  - Magma 2.5.4
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.7, CUDNN_VERSION=8.5.0, CXX_COMPILER=C:/actions-runner/_work/pytorch/pytorch/builder/windows/tmp_bin/sccache-cl.exe, CXX_FLAGS=/DWIN32 /D_WINDOWS /GR /EHsc /w /bigobj -DUSE_PTHREADPOOL -openmp:experimental -IC:/actions-runner/_work/pytorch/pytorch/builder/windows/mkl/include -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.13.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.14.1+cu117
OpenCV: 4.8.0
MMCV: 1.7.1
pcan: 0.1.0+0650969
------------------------------------------------------------

2023-09-21 15:59:57,977 - pcan - INFO - Distributed training: False
2023-09-21 15:59:58,199 - pcan - INFO - Config:
model = dict(
    type='QuasiDenseFasterRCNN',
    pretrained='torchvision://resnet50',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=1,
        norm_cfg=dict(type='BN', requires_grad=True),
        norm_eval=True,
        style='pytorch'),
    neck=dict(
        type='FPN',
        in_channels=[256, 512, 1024, 2048],
        out_channels=256,
        num_outs=5),
    rpn_head=dict(
        type='RPNHead',
        in_channels=256,
        feat_channels=256,
        anchor_generator=dict(
            type='AnchorGenerator',
            scales=[8],
            ratios=[0.5, 1.0, 2.0],
            strides=[4, 8, 16, 32, 64]),
        bbox_coder=dict(
            type='DeltaXYWHBBoxCoder',
            target_means=[0.0, 0.0, 0.0, 0.0],
            target_stds=[1.0, 1.0, 1.0, 1.0]),
        loss_cls=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0),
        loss_bbox=dict(
            type='SmoothL1Loss', beta=0.1111111111111111, loss_weight=1.0)),
    roi_head=dict(
        type='QuasiDenseRoIHead',
        bbox_roi_extractor=dict(
            type='SingleRoIExtractor',
            roi_layer=dict(type='RoIAlign', output_size=7, sampling_ratio=0),
            out_channels=256,
            featmap_strides=[4, 8, 16, 32]),
        bbox_head=dict(
            type='Shared2FCBBoxHead',
            in_channels=256,
            fc_out_channels=1024,
            roi_feat_size=7,
            num_classes=8,
            bbox_coder=dict(
                type='DeltaXYWHBBoxCoder',
                target_means=[0.0, 0.0, 0.0, 0.0],
                target_stds=[0.1, 0.1, 0.2, 0.2]),
            reg_class_agnostic=False,
            loss_cls=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
            loss_bbox=dict(type='SmoothL1Loss', beta=1.0, loss_weight=1.0)),
        track_roi_extractor=dict(
            type='SingleRoIExtractor',
            roi_layer=dict(type='RoIAlign', output_size=7, sampling_ratio=0),
            out_channels=256,
            featmap_strides=[4, 8, 16, 32]),
        track_head=dict(
            type='QuasiDenseEmbedHead',
            num_convs=4,
            num_fcs=1,
            embed_channels=256,
            norm_cfg=dict(type='GN', num_groups=32),
            loss_track=dict(type='MultiPosCrossEntropyLoss', loss_weight=0.25),
            loss_track_aux=dict(
                type='L2Loss',
                neg_pos_ub=3,
                pos_margin=0,
                neg_margin=0.3,
                hard_mining=True,
                loss_weight=1.0))),
    tracker=dict(
        type='QuasiDenseEmbedTracker',
        init_score_thr=0.7,
        obj_score_thr=0.3,
        match_score_thr=0.5,
        memo_tracklet_frames=10,
        memo_backdrop_frames=1,
        memo_momentum=0.8,
        nms_conf_thr=0.5,
        nms_backdrop_iou_thr=0.3,
        nms_class_iou_thr=0.7,
        with_cats=True,
        match_metric='bisoftmax'),
    train_cfg=dict(
        rpn=dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.7,
                neg_iou_thr=0.3,
                min_pos_iou=0.3,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=256,
                pos_fraction=0.5,
                neg_pos_ub=-1,
                add_gt_as_proposals=False),
            allowed_border=-1,
            pos_weight=-1,
            debug=False),
        rpn_proposal=dict(
            nms_across_levels=False,
            nms_pre=2000,
            nms_post=1000,
            max_num=1000,
            nms_thr=0.7,
            min_bbox_size=0),
        rcnn=dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.5,
                neg_iou_thr=0.5,
                min_pos_iou=0.5,
                match_low_quality=False,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=512,
                pos_fraction=0.25,
                neg_pos_ub=-1,
                add_gt_as_proposals=True),
            pos_weight=-1,
            debug=False),
        embed=dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.7,
                neg_iou_thr=0.3,
                min_pos_iou=0.5,
                match_low_quality=False,
                ignore_iof_thr=-1),
            sampler=dict(
                type='CombinedSampler',
                num=256,
                pos_fraction=0.5,
                neg_pos_ub=3,
                add_gt_as_proposals=True,
                pos_sampler=dict(type='InstanceBalancedPosSampler'),
                neg_sampler=dict(
                    type='IoUBalancedNegSampler',
                    floor_thr=-1,
                    floor_fraction=0,
                    num_bins=3)))),
    test_cfg=dict(
        rpn=dict(
            nms_across_levels=False,
            nms_pre=1000,
            nms_post=1000,
            max_num=1000,
            nms_thr=0.7,
            min_bbox_size=0),
        rcnn=dict(
            score_thr=0.5,
            nms=dict(type='nms', iou_threshold=0.5),
            max_per_img=100)))
dataset_type = 'BDDVideoDataset'
data_root = '../data/guandao/'
img_norm_cfg = dict(
    mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
    dict(type='LoadMultiImagesFromFile'),
    dict(type='SeqLoadAnnotations', with_bbox=True, with_ins_id=True),
    dict(type='SeqResize', img_scale=(480, 640), keep_ratio=True),
    dict(type='SeqRandomFlip', share_params=True, flip_ratio=0.5),
    dict(
        type='SeqNormalize',
        mean=[123.675, 116.28, 103.53],
        std=[58.395, 57.12, 57.375],
        to_rgb=True),
    dict(type='SeqPad', size_divisor=32),
    dict(type='SeqDefaultFormatBundle'),
    dict(
        type='SeqCollect',
        keys=['img', 'gt_bboxes', 'gt_labels', 'gt_match_indices'],
        ref_prefix='ref')
]
test_pipeline = [
    dict(type='LoadImageFromFile'),
    dict(
        type='MultiScaleFlipAug',
        img_scale=(480, 640),
        flip=False,
        transforms=[
            dict(type='Resize', keep_ratio=True),
            dict(type='RandomFlip'),
            dict(
                type='Normalize',
                mean=[123.675, 116.28, 103.53],
                std=[58.395, 57.12, 57.375],
                to_rgb=True),
            dict(type='Pad', size_divisor=32),
            dict(type='ImageToTensor', keys=['img']),
            dict(type='VideoCollect', keys=['img'])
        ])
]
data = dict(
    samples_per_gpu=2,
    workers_per_gpu=2,
    train=[
        dict(
            type='BDDVideoDataset',
            ann_file='../data/guandao/labels/labels_j/train_food.json',
            img_prefix='../data/guandao/images/JPEGImages_j/imagetrainj',
            key_img_sampler=dict(interval=1),
            ref_img_sampler=dict(num_ref_imgs=1, scope=3, method='uniform'),
            pipeline=[
                dict(type='LoadMultiImagesFromFile'),
                dict(
                    type='SeqLoadAnnotations',
                    with_bbox=True,
                    with_ins_id=True),
                dict(type='SeqResize', img_scale=(480, 640), keep_ratio=True),
                dict(type='SeqRandomFlip', share_params=True, flip_ratio=0.5),
                dict(
                    type='SeqNormalize',
                    mean=[123.675, 116.28, 103.53],
                    std=[58.395, 57.12, 57.375],
                    to_rgb=True),
                dict(type='SeqPad', size_divisor=32),
                dict(type='SeqDefaultFormatBundle'),
                dict(
                    type='SeqCollect',
                    keys=['img', 'gt_bboxes', 'gt_labels', 'gt_match_indices'],
                    ref_prefix='ref')
            ]),
        dict(
            type='BDDVideoDataset',
            load_as_video=False,
            ann_file='../data/guandao/labels/labels_j/train_food.json',
            img_prefix='../data/guandao/images/JPEGImages_j/imagetrainj',
            pipeline=[
                dict(type='LoadMultiImagesFromFile'),
                dict(
                    type='SeqLoadAnnotations',
                    with_bbox=True,
                    with_ins_id=True),
                dict(type='SeqResize', img_scale=(480, 640), keep_ratio=True),
                dict(type='SeqRandomFlip', share_params=True, flip_ratio=0.5),
                dict(
                    type='SeqNormalize',
                    mean=[123.675, 116.28, 103.53],
                    std=[58.395, 57.12, 57.375],
                    to_rgb=True),
                dict(type='SeqPad', size_divisor=32),
                dict(type='SeqDefaultFormatBundle'),
                dict(
                    type='SeqCollect',
                    keys=['img', 'gt_bboxes', 'gt_labels', 'gt_match_indices'],
                    ref_prefix='ref')
            ])
    ],
    val=dict(
        type='BDDVideoDataset',
        ann_file='../data/guandao/labels/labels_j/val_food.json',
        img_prefix='../data/guandao/images/JPEGImages_j/imagevalj',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(480, 640),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='VideoCollect', keys=['img'])
                ])
        ]),
    test=dict(
        type='BDDVideoDataset',
        ann_file='../data/guandao/labels/labels_j/test_food.json',
        img_prefix='../data/guandao/images/JPEGImages_j/imagetestj',
        pipeline=[
            dict(type='LoadImageFromFile'),
            dict(
                type='MultiScaleFlipAug',
                img_scale=(480, 640),
                flip=False,
                transforms=[
                    dict(type='Resize', keep_ratio=True),
                    dict(type='RandomFlip'),
                    dict(
                        type='Normalize',
                        mean=[123.675, 116.28, 103.53],
                        std=[58.395, 57.12, 57.375],
                        to_rgb=True),
                    dict(type='Pad', size_divisor=32),
                    dict(type='ImageToTensor', keys=['img']),
                    dict(type='VideoCollect', keys=['img'])
                ])
        ]))
optimizer = dict(type='SGD', lr=0.04, momentum=0.9, weight_decay=0.0001)
optimizer_config = dict(grad_clip=None)
lr_config = dict(
    policy='step',
    warmup='linear',
    warmup_iters=1000,
    warmup_ratio=0.001,
    step=[8, 11])
checkpoint_config = dict(interval=1)
log_config = dict(interval=50, hooks=[dict(type='TextLoggerHook')])
total_epochs = 12
dist_params = dict(backend='nccl')
log_level = 'INFO'
load_from = None
resume_from = None
workflow = [('train', 1)]
evaluation = dict(metric=['bbox', 'track'], interval=2)
work_dir = './work_dirs\qdtrack-frcnn_r50_fpn_12e_bdd100k_evalseg'
gpu_ids = range(0, 1)

2023-09-21 15:59:58,427 - mmdet - INFO - load model from: torchvision://resnet50
2023-09-21 15:59:58,427 - mmdet - INFO - load checkpoint from torchvision path: torchvision://resnet50
2023-09-21 15:59:58,532 - mmdet - WARNING - The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

loading annotations into memory...
Done (t=0.01s)
creating index...
C:\Users\Admin\Desktop\pcan-main\pcan\datasets\parsers\coco_api.py:21: UserWarning: mmpycocotools is deprecated. Please install official pycocotools by "pip install pycocotools"
  UserWarning)
index created!
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
2023-09-21 15:59:59,230 - pcan - INFO - Start running, host: Admin@PS2023QYZLHGNB, work_dir: C:\Users\Admin\Desktop\pcan-main\tools\work_dirs\qdtrack-frcnn_r50_fpn_12e_bdd100k_evalseg
2023-09-21 15:59:59,230 - pcan - INFO - Hooks will be executed in the following order:
before_run:
(VERY_HIGH   ) StepLrUpdaterHook                  
(NORMAL      ) CheckpointHook                     
(NORMAL      ) EvalHook                           
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
before_train_epoch:
(VERY_HIGH   ) StepLrUpdaterHook                  
(NORMAL      ) EvalHook                           
(LOW         ) IterTimerHook                      
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
before_train_iter:
(VERY_HIGH   ) StepLrUpdaterHook                  
(LOW         ) IterTimerHook                      
 -------------------- 
after_train_iter:
(ABOVE_NORMAL) OptimizerHook                      
(NORMAL      ) CheckpointHook                     
(NORMAL      ) EvalHook                           
(LOW         ) IterTimerHook                      
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
after_train_epoch:
(NORMAL      ) CheckpointHook                     
(NORMAL      ) EvalHook                           
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
before_val_epoch:
(LOW         ) IterTimerHook                      
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
before_val_iter:
(LOW         ) IterTimerHook                      
 -------------------- 
after_val_iter:
(LOW         ) IterTimerHook                      
 -------------------- 
after_val_epoch:
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
after_run:
(VERY_LOW    ) TextLoggerHook                     
 -------------------- 
2023-09-21 15:59:59,230 - pcan - INFO - workflow: [('train', 1)], max: 12 epochs
2023-09-21 15:59:59,230 - pcan - INFO - Checkpoints will be saved to C:\Users\Admin\Desktop\pcan-main\tools\work_dirs\qdtrack-frcnn_r50_fpn_12e_bdd100k_evalseg by HardDiskBackend.
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
C:\Anaconda\envs\pcan\lib\site-packages\mmdet\models\dense_heads\rpn_head.py:180: UserWarning: In rpn_proposal or test_cfg, nms_thr has been moved to a dict named nms as iou_threshold, max_num has been renamed as max_per_img, name of original arguments and the way to specify iou_threshold of NMS will be deprecated.
  'In rpn_proposal or test_cfg, '
2023-09-21 16:00:16,268 - pcan - INFO - Epoch [1][50/617]	lr: 1.998e-03, eta: 0:41:44, time: 0.341, data_time: 0.158, memory: 2301, loss_rpn_cls: nan, loss_rpn_bbox: nan, loss_cls: nan, acc: 90.5784, loss_bbox: nan, loss_track: nan, loss_track_aux: nan, loss: nan
2023-09-21 16:00:23,313 - pcan - INFO - Epoch [1][100/617]	lr: 3.996e-03, eta: 0:29:17, time: 0.141, data_time: 0.003, memory: 2301, loss_rpn_cls: nan, loss_rpn_bbox: nan, loss_cls: nan, acc: 88.5912, loss_bbox: nan, loss_track: nan, loss_track_aux: nan, loss: nan
2023-09-21 16:00:30,334 - pcan - INFO - Epoch [1][150/617]	lr: 5.994e-03, eta: 0:25:03, time: 0.140, data_time: 0.003, memory: 2301, loss_rpn_cls: nan, loss_rpn_bbox: nan, loss_cls: nan, acc: 89.7586, loss_bbox: nan, loss_track: nan, loss_track_aux: nan, loss: nan
2023-09-21 16:00:37,322 - pcan - INFO - Epoch [1][200/617]	lr: 7.992e-03, eta: 0:22:51, time: 0.140, data_time: 0.003, memory: 2301, loss_rpn_cls: nan, loss_rpn_bbox: nan, loss_cls: nan, acc: 92.1037, loss_bbox: nan, loss_track: nan, loss_track_aux: nan, loss: nan
2023-09-21 16:00:44,367 - pcan - INFO - Epoch [1][250/617]	lr: 9.990e-03, eta: 0:21:31, time: 0.141, data_time: 0.003, memory: 2301, loss_rpn_cls: nan, loss_rpn_bbox: nan, loss_cls: nan, acc: 86.1733, loss_bbox: nan, loss_track: nan, loss_track_aux: nan, loss: nan
2023-09-21 16:00:51,404 - pcan - INFO - Epoch [1][300/617]	lr: 1.199e-02, eta: 0:20:35, time: 0.141, data_time: 0.003, memory: 2301, loss_rpn_cls: nan, loss_rpn_bbox: nan, loss_cls: nan, acc: 89.6032, loss_bbox: nan, loss_track: nan, loss_track_aux: nan, loss: nan
2023-09-21 16:00:58,340 - pcan - INFO - Epoch [1][350/617]	lr: 1.399e-02, eta: 0:19:51, time: 0.139, data_time: 0.003, memory: 2301, loss_rpn_cls: nan, loss_rpn_bbox: nan, loss_cls: nan, acc: 90.3079, loss_bbox: nan, loss_track: nan, loss_track_aux: nan, loss: nan
2023-09-21 16:01:05,295 - pcan - INFO - Epoch [1][400/617]	lr: 1.598e-02, eta: 0:19:16, time: 0.139, data_time: 0.003, memory: 2301, loss_rpn_cls: nan, loss_rpn_bbox: nan, loss_cls: nan, acc: 88.3841, loss_bbox: nan, loss_track: nan, loss_track_aux: nan, loss: nan
2023-09-21 16:01:12,252 - pcan - INFO - Epoch [1][450/617]	lr: 1.798e-02, eta: 0:18:48, time: 0.139, data_time: 0.003, memory: 2301, loss_rpn_cls: nan, loss_rpn_bbox: nan, loss_cls: nan, acc: 91.9174, loss_bbox: nan, loss_track: nan, loss_track_aux: nan, loss: nan
2023-09-21 16:01:19,277 - pcan - INFO - Epoch [1][500/617]	lr: 1.998e-02, eta: 0:18:25, time: 0.140, data_time: 0.003, memory: 2301, loss_rpn_cls: nan, loss_rpn_bbox: nan, loss_cls: nan, acc: 89.9358, loss_bbox: nan, loss_track: nan, loss_track_aux: nan, loss: nan
2023-09-21 16:01:26,273 - pcan - INFO - Epoch [1][550/617]	lr: 2.198e-02, eta: 0:18:04, time: 0.140, data_time: 0.003, memory: 2301, loss_rpn_cls: nan, loss_rpn_bbox: nan, loss_cls: nan, acc: 87.2205, loss_bbox: nan, loss_track: nan, loss_track_aux: nan, loss: nan
2023-09-21 16:01:33,275 - pcan - INFO - Epoch [1][600/617]	lr: 2.398e-02, eta: 0:17:46, time: 0.140, data_time: 0.003, memory: 2301, loss_rpn_cls: nan, loss_rpn_bbox: nan, loss_cls: nan, acc: 90.9714, loss_bbox: nan, loss_track: nan, loss_track_aux: nan, loss: nan
2023-09-21 16:01:35,962 - pcan - INFO - Saving checkpoint at 1 epochs
2023-09-21 16:01:52,579 - pcan - INFO - Epoch [2][50/617]	lr: 2.665e-02, eta: 0:18:20, time: 0.298, data_time: 0.156, memory: 2301, loss_rpn_cls: nan, loss_rpn_bbox: nan, loss_cls: nan, acc: 90.8333, loss_bbox: nan, loss_track: nan, loss_track_aux: nan, loss: nan
2023-09-21 16:01:59,578 - pcan - INFO - Epoch [2][100/617]	lr: 2.865e-02, eta: 0:18:01, time: 0.140, data_time: 0.003, memory: 2301, loss_rpn_cls: nan, loss_rpn_bbox: nan, loss_cls: nan, acc: 88.6841, loss_bbox: nan, loss_track: nan, loss_track_aux: nan, loss: nan
2023-09-21 16:02:06,571 - pcan - INFO - Epoch [2][150/617]	lr: 3.065e-02, eta: 0:17:43, time: 0.140, data_time: 0.003, memory: 2301, loss_rpn_cls: nan, loss_rpn_bbox: nan, loss_cls: nan, acc: 93.1286, loss_bbox: nan, loss_track: nan, loss_track_aux: nan, loss: nan
2023-09-21 16:02:13,572 - pcan - INFO - Epoch [2][200/617]	lr: 3.265e-02, eta: 0:17:27, time: 0.140, data_time: 0.003, memory: 2301, loss_rpn_cls: nan, loss_rpn_bbox: nan, loss_cls: nan, acc: 86.5786, loss_bbox: nan, loss_track: nan, loss_track_aux: nan, loss: nan
2023-09-21 16:02:20,596 - pcan - INFO - Epoch [2][250/617]	lr: 3.465e-02, eta: 0:17:12, time: 0.140, data_time: 0.003, memory: 2301, loss_rpn_cls: nan, loss_rpn_bbox: nan, loss_cls: nan, acc: 88.9562, loss_bbox: nan, loss_track: nan, loss_track_aux: nan, loss: nan
2023-09-21 16:02:27,592 - pcan - INFO - Epoch [2][300/617]	lr: 3.664e-02, eta: 0:16:58, time: 0.140, data_time: 0.003, memory: 2301, loss_rpn_cls: nan, loss_rpn_bbox: nan, loss_cls: nan, acc: 89.3254, loss_bbox: nan, loss_track: nan, loss_track_aux: nan, loss: nan
2023-09-21 16:02:34,558 - pcan - INFO - Epoch [2][350/617]	lr: 3.864e-02, eta: 0:16:44, time: 0.139, data_time: 0.003, memory: 2301, loss_rpn_cls: nan, loss_rpn_bbox: nan, loss_cls: nan, acc: 91.2230, loss_bbox: nan, loss_track: nan, loss_track_aux: nan, loss: nan
2023-09-21 16:02:41,542 - pcan - INFO - Epoch [2][400/617]	lr: 4.000e-02, eta: 0:16:31, time: 0.140, data_time: 0.003, memory: 2301, loss_rpn_cls: nan, loss_rpn_bbox: nan, loss_cls: nan, acc: 91.4397, loss_bbox: nan, loss_track: nan, loss_track_aux: nan, loss: nan
2023-09-21 16:02:48,506 - pcan - INFO - Epoch [2][450/617]	lr: 4.000e-02, eta: 0:16:19, time: 0.139, data_time: 0.003, memory: 2301, loss_rpn_cls: nan, loss_rpn_bbox: nan, loss_cls: nan, acc: 89.0595, loss_bbox: nan, loss_track: nan, loss_track_aux: nan, loss: nan
2023-09-21 16:02:55,531 - pcan - INFO - Epoch [2][500/617]	lr: 4.000e-02, eta: 0:16:07, time: 0.140, data_time: 0.003, memory: 2301, loss_rpn_cls: nan, loss_rpn_bbox: nan, loss_cls: nan, acc: 86.6459, loss_bbox: nan, loss_track: nan, loss_track_aux: nan, loss: nan
2023-09-21 16:03:02,480 - pcan - INFO - Epoch [2][550/617]	lr: 4.000e-02, eta: 0:15:55, time: 0.139, data_time: 0.003, memory: 2301, loss_rpn_cls: nan, loss_rpn_bbox: nan, loss_cls: nan, acc: 87.5785, loss_bbox: nan, loss_track: nan, loss_track_aux: nan, loss: nan
2023-09-21 16:03:09,487 - pcan - INFO - Epoch [2][600/617]	lr: 4.000e-02, eta: 0:15:44, time: 0.140, data_time: 0.003, memory: 2301, loss_rpn_cls: nan, loss_rpn_bbox: nan, loss_cls: nan, acc: 91.5429, loss_bbox: nan, loss_track: nan, loss_track_aux: nan, loss: nan
2023-09-21 16:03:12,165 - pcan - INFO - Saving checkpoint at 2 epochs
completed: 0, elapsed: 0sEvaluating BDD Results...
Traceback (most recent call last):
  File "C:/Users/Admin/Desktop/pcan-main/tools/train.py", line 170, in <module>
    main()
  File "C:/Users/Admin/Desktop/pcan-main/tools/train.py", line 166, in main
    meta=meta)
  File "C:\Users\Admin\Desktop\pcan-main\pcan\apis\train.py", line 123, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "C:\Anaconda\envs\pcan\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "C:\Anaconda\envs\pcan\lib\site-packages\mmcv\runner\epoch_based_runner.py", line 58, in train
    self.call_hook('after_train_epoch')
  File "C:\Anaconda\envs\pcan\lib\site-packages\mmcv\runner\base_runner.py", line 317, in call_hook
    getattr(hook, fn_name)(self)
  File "C:\Users\Admin\Desktop\pcan-main\pcan\core\evaluation\eval_hooks.py", line 14, in after_train_epoch
    self.evaluate(runner, results)
  File "C:\Anaconda\envs\pcan\lib\site-packages\mmdet\core\evaluation\eval_hooks.py", line 177, in evaluate
    results, logger=runner.logger, **self.eval_kwargs)
  File "C:\Users\Admin\Desktop\pcan-main\pcan\datasets\coco_video_dataset.py", line 319, in evaluate
    class_average=mot_class_average)
  File "C:\Users\Admin\Desktop\pcan-main\pcan\core\evaluation\mot.py", line 190, in eval_mot
    assert len(all_results) == len(anns['images'])
AssertionError

**Comment by dccdcc7** [comment]
hello, have you encoutered
ModuleNotFoundError: No module named 'mmcv._ext'
when you performed steps mentioned in GET_STARTED.md?
thank u

**Comment by cui19981127** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SysCV/pcan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月19日(星期一) 晚上10:27
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [SysCV/pcan] AssertionError (Issue #33)





 
hello, have you encoutered
 ModuleNotFoundError: No module named 'mmcv._ext'
 when you performed steps mentioned in GET_STARTED.md?
 thank u
 
—The version of the mmcv library is incorrect
