### ISSUE TITLE
用于测试的demo后续会更新吗？

### ISSUE THREAD

**Issue by heuyu980817** [SysCV/pcan#4]
我试着将mmdetection的demo中的video_demo.py拼接到您的网络中，显示如下问题：
Traceback (most recent call last):
  File "demo/video_demo.py", line 60, in <module>
    main()
  File "demo/video_demo.py", line 35, in main
    model = init_detector(args.config, args.checkpoint, device=args.device)
  File "/home/zhy/anaconda3/envs/pcan/lib/python3.7/site-packages/mmdet/apis/inference.py", line 39, in init_detector
    model = build_detector(config.model, test_cfg=config.get('test_cfg'))
  File "/home/zhy/anaconda3/envs/pcan/lib/python3.7/site-packages/mmdet/models/builder.py", line 77, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/zhy/anaconda3/envs/pcan/lib/python3.7/site-packages/mmdet/models/builder.py", line 34, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/zhy/anaconda3/envs/pcan/lib/python3.7/site-packages/mmcv/utils/registry.py", line 172, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'QuasiDenseMaskRCNN is not in the detector registry'
(pcan) zhy@king:~/pcan$ python test_video.py demo/demo.mp4 configs/segtrack-frcnn_r50_fpn_12e_bdd10k.py checkpoints/pcan_pretrained_model.pth --show
configs/segtrack-frcnn_r50_fpn_12e_bdd10k.py
Traceback (most recent call last):
  File "test_video.py", line 61, in <module>
    main()
  File "test_video.py", line 36, in main
    model = init_detector(args.config, args.checkpoint, device=args.device)
  File "/home/zhy/anaconda3/envs/pcan/lib/python3.7/site-packages/mmdet/apis/inference.py", line 39, in init_detector
    model = build_detector(config.model, test_cfg=config.get('test_cfg'))
  File "/home/zhy/anaconda3/envs/pcan/lib/python3.7/site-packages/mmdet/models/builder.py", line 77, in build_detector
    return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/zhy/anaconda3/envs/pcan/lib/python3.7/site-packages/mmdet/models/builder.py", line 34, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/zhy/anaconda3/envs/pcan/lib/python3.7/site-packages/mmcv/utils/registry.py", line 172, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'QuasiDenseMaskRCNN is not in the detector registry'
查找相关问题应该是处在setup.py那个文件。
希望您对我的疑惑进行解答谢谢

**Comment by lkeab** [comment]
Hi, we provided our visual demo script [here](https://github.com/SysCV/pcan/blob/main/docs/GET_STARTED.md#visualization-script). Also, please follow the [installing document](https://github.com/SysCV/pcan/blob/main/docs/INSTALL.md) to set up the required environment.

**Comment by lkeab** [comment]
You could also find more demo videos in our projects website

**Comment by heuyu980817** [comment]
thanks，hope u can get higher achievement

**Comment by cui19981127** [comment]
Your visual script can only run annotated information, how do I run unannotated videos to get results
